services:
    db:
        image: mysql:latest
        env_file: .env
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
    backend:
        build: ./API
        ports:
            - "3000:3000"
        volumes:
            - ./API:/app
            - /app/node_modules
        env_file: ./API/.env
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
    frontend:
        build: ./UI
        ports:
            - "5173:5173"
        volumes:
            - ./UI:/app
            - /app/node_modules
        depends_on:
            - backend
    redis:
        image: redis:8.0-rc1-alpine
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

    static:
        build: ./static
        ports:
            - "3001:80"
        volumes:
            - ./static/uploads:/usr/share/nginx/html/uploads
        depends_on:
            - backend
volumes:
    db_data:
    redis_data:
